import React from 'react';

const DeveloperToolsRouteComponent: React.FC = () => {
  // MCP servers in the developer tools category
  const mcpServers = [
    { name: "21st-dev/Magic-MCP", description: "Create crafted UI components inspired by the best 21st.dev design engineers." },
    { name: "aashari/mcp-server-atlassian-bitbucket", description: "Atlassian Bitbucket Cloud integration. Enables AI systems to interact with repositories, pull requests, workspaces, and code in real time." },
    { name: "aashari/mcp-server-atlassian-confluence", description: "Atlassian Confluence Cloud integration. Enables AI systems to interact with Confluence spaces, pages, and content with automatic ADF to Markdown conversion." },
    { name: "aashari/mcp-server-atlassian-jira", description: "Atlassian Jira Cloud integration. Enables AI systems to interact with Jira projects, issues, comments, and related development information in real time." },
    { name: "abrinsmead/mindpilot-mcp", description: "Visualizes code, architecture and other concepts as mermaid diagrams in a locally hosted web app. Just ask your agent to \"show me this in a diagram\"." },
    { name: "admica/FileScopeMCP", description: "Analyzes your codebase identifying important files based on dependency relationships. Generates diagrams and importance scores, helping AI assistants understand the codebase." },
    { name: "akramIOT/MCP_AI_SOC_Sher", description: "MCP Server to do dynamic AI SOC Security Threat analysis for a Text2SQL AI Agent." },
    { name: "alimo7amed93/webhook-tester-mcp", description: "A FastMCP-based server for interacting with webhook-test.com. Enables users to create, retrieve, and delete webhooks locally using Claude." },
    { name: "ambar/simctl-mcp", description: "A MCP server implementation for iOS Simulator control." },
    { name: "api7/apisix-mcp", description: "MCP Server that support for querying and managing all resource in Apache APISIX." },
    { name: "ArchAI-Labs/fastmcp-sonarqube-metrics", description: "A Model Context Protocol (MCP) server that provides a set of tools for retrieving information about SonarQube projects like metrics (actual and historical), issues, health status." },
    { name: "artmann/package-registry-mcp", description: "MCP server for searching and getting up-to-date information about NPM, Cargo, PyPi, and NuGet packages." },
    { name: "wyattjoh/jsr-mcp", description: "Model Context Protocol server for the JSR (JavaScript Registry)" },
    { name: "augmnt/augments-mcp-server", description: "Transform Claude Code with intelligent, real-time access to 90+ framework documentation sources. Get accurate, up-to-date code generation that follows current best practices for React, Next.js, Laravel, FastAPI, Tailwind CSS, and more." },
    { name: "automation-ai-labs/mcp-link", description: "Seamlessly Integrate Any API with AI Agents (with OpenAPI Schema)" },
    { name: "axliupore/mcp-code-runner", description: "An MCP server for running code locally via Docker and supporting multiple programming languages." },
    { name: "azer/react-analyzer-mcp", description: "Analyze React code locally, generate docs / llm.txt for whole project at once" },
    { name: "buildkite/buildkite-mcp-server", description: "Official MCP server for Buildkite. Create new pipelines, diagnose and fix failures, trigger builds, monitor job queues, and more." },
    { name: "Chunkydotdev/bldbl-mcp", description: "Official MCP server for Buildable AI-powered development platform bldbl.dev. Enables AI assistants to manage tasks, track progress, get project context, and collaborate with humans on software projects." },
    { name: "CircleCI/mcp-server-circleci", description: "Enable AI Agents to fix build failures from CircleCI." },
    { name: "cjo4m06/mcp-shrimp-task-manager", description: "A programming-focused task management system that boosts coding agents like Cursor AI with advanced task memory, self-reflection, and dependency management. ShrimpTaskManager" },
    { name: "ckanthony/gin-mcp", description: "A zero-configuration Go library to automatically expose existing Gin web framework APIs as MCP tools." },
    { name: "ckreiling/mcp-server-docker", description: "Integrate with Docker to manage containers, images, volumes, and networks." },
    { name: "CodeLogicIncEngineering/codelogic-mcp-server", description: "Official MCP server for CodeLogic, providing access to code dependency analytics, architectural risk analysis, and impact assessment tools." },
    { name: "Comet-ML/Opik-MCP", description: "Use natural language to explore LLM observability, traces, and monitoring data captured by Opik." },
    { name: "ConfigCat/mcp-server", description: "MCP server for interacting with ConfigCat feature flag platform. Supports managing feature flags, configs, environments, products and organizations." },
    { name: "cqfn/aibolit-mcp-server", description: "Helping Your AI Agent Identify Hotspots for Refactoring; Help AI Understand How to 'Make Code Better'" },
    { name: "currents-dev/currents-mcp", description: "Enable AI Agents to fix Playwright test failures reported to Currents." },
    { name: "davidan90/time-node-mcp", description: "Timezone-aware date and time operations with support for IANA timezones, timezone conversion, and Daylight Saving Time handling." },
    { name: "davidlin2k/pox-mcp-server", description: "MCP server for the POX SDN controller to provides network control and management capabilities." },
    { name: "delano/postman-mcp-server", description: "Interact with Postman API" },
    { name: "deploy-mcp/deploy-mcp", description: "Universal deployment tracker for AI assistants with live status badges and deployment monitoring" },
    { name: "docker/hub-mcp", description: "Official MCP server to interact with Docker Hub, providing access to repositories, hub search and Docker Hardened Images" },
    { name: "endorhq/cli", description: "Endor lets your AI agents run services like MariaDB, Postgres, Redis, Memcached, Alpine, or Valkey in isolated sandboxes. Get pre-configured applications that boot in less than 5 seconds." },
    { name: "etsd-tech/mcp-pointer", description: "Visual DOM element selector for agentic coding tools. Chrome extension + MCP server bridge for Claude Code, Cursor, Windsurf etc. Option+Click to capture elements." },
    { name: "flipt-io/mcp-server-flipt", description: "Enable AI assistants to interact with your feature flags in Flipt." },
    { name: "freema/mcp-design-system-extractor", description: "Extracts component information from Storybook design systems. Provides HTML, styles, props, dependencies, theme tokens and component metadata for AI-powered design system analysis." },
    { name: "gitkraken/gk-cli", description: "A CLI for interacting with GitKraken APIs. Includes an MCP server via gk mcp that not only wraps GitKraken APIs, but also Jira, GitHub, GitLab, and more. Works with local tools and remote services." },
    { name: "GLips/Figma-Context-MCP", description: "Provide coding agents direct access to Figma data to help them one-shot design implementation." },
    { name: "gofireflyio/firefly-mcp", description: "Integrates, discovers, manages, and codifies cloud resources with Firefly." },
    { name: "gorosun/unified-diff-mcp", description: "Generate and visualize unified diff comparisons with beautiful HTML/PNG output, supporting side-by-side and line-by-line views for filesystem dry-run integration" },
    { name: "Govcraft/rust-docs-mcp-server", description: "Provides up-to-date documentation context for a specific Rust crate to LLMs via an MCP tool, using semantic search (embeddings) and LLM summarization." },
    { name: "PromptExecution/cratedocs-mcp", description: "Outputs short-form Rust crate derived traits,interfaces, etc. from AST (uses same api as rust-analyzer), output limits (token estimation) & crate docs w/regex stripping." },
    { name: "HainanZhao/mcp-gitlab-jira", description: "Unified MCP server for GitLab and Jira: manage projects, merge requests, files, releases and tickets with AI agents." },
    { name: "haris-musa/excel-mcp-server", description: "An Excel manipulation server providing workbook creation, data operations, formatting, and advanced features (charts, pivot tables, formulae)." },
    { name: "higress-group/higress-ops-mcp-server", description: "MCP server that provides comprehensive tools for managing Higress gateway configurations and operations." },
    { name: "hijaz/postmancer", description: "A MCP server for replacing Rest Clients like Postman/Insomnia, by allowing your LLM to maintain and use api collections." },
    { name: "hloiseaufcms/mcp-gopls", description: "A MCP server for interacting with Go's Language Server Protocol (gopls) and benefit from advanced Go code analysis features." },
    { name: "hungthai1401/bruno-mcp", description: "A MCP server for interacting with Bruno API Client." },
    { name: "hyperb1iss/droidmind", description: "Control Android devices with AI through MCP, enabling device control, debugging, system analysis, and UI automation with a comprehensive security framework." },
    { name: "Hypersequent/qasphere-mcp", description: "Integration with QA Sphere test management system, enabling LLMs to discover, summarize, and interact with test cases directly from AI-powered IDEs" },
    { name: "idosal/git-mcp", description: "gitmcp.io is a generic remote MCP server to connect to ANY GitHub repository or project for documentation" },
    { name: "IlyaGulya/gradle-mcp-server", description: "Gradle integration using the Gradle Tooling API to inspect projects, execute tasks, and run tests with per-test result reporting" },
    { name: "promptexecution/just-mcp", description: "Justfile integration that enables LLMs to execute any CLI or script commands with parameters safely and easily, with environment variable support and comprehensive testing." },
    { name: "InditexTech/mcp-server-simulator-ios-idb", description: "A Model Context Protocol (MCP) server that enables LLMs to interact with iOS simulators (iPhone, iPad, etc.) through natural language commands." },
    { name: "InhiblabCore/mcp-image-compression", description: "MCP server for local compression of various image formats." },
    { name: "InsForge/insforge-mcp", description: "AI-native backend-as-a-service platform enabling AI agents to build and manage full-stack applications. Provides Auth, Database (PostgreSQL), Storage, and Functions as production-grade infrastructure, reducing MVP development time from weeks to hours." },
    { name: "Inspizzz/jetbrains-datalore-mcp", description: "MCP server for interacting with cloud deployments of Jetbrains Datalore platform. Fully incorporated Datalore API ( run, run interactively, get run data, fetch files )" },
    { name: "ios-simulator-mcp", description: "A Model Context Protocol (MCP) server for interacting with iOS simulators. This server allows you to interact with iOS simulators by getting information about them, controlling UI interactions, and inspecting UI elements." },
    { name: "isaacphi/mcp-language-server", description: "MCP Language Server helps MCP enabled clients navigate codebases more easily by giving them access to semantic tools like get definition, references, rename, and diagnostics." },
    { name: "IvanAmador/vercel-ai-docs-mcp", description: "A Model Context Protocol (MCP) server that provides AI-powered search and querying capabilities for the Vercel AI SDK documentation." },
    { name: "j4c0bs/mcp-server-sql-analyzer", description: "MCP server that provides SQL analysis, linting, and dialect conversion using SQLGlot" },
    { name: "janreges/ai-distiller-mcp", description: "Extracts essential code structure from large codebases into AI-digestible format, helping AI agents write code that correctly uses existing APIs on the first attempt." },
    { name: "jasonjmcghee/claude-debugs-for-you", description: "An MCP Server and VS Code Extension which enables (language agnostic) automatic debugging via breakpoints and expression evaluation." },
    { name: "jetbrains/mcpProxy", description: "Connect to JetBrains IDE" },
    { name: "Jktfe/serveMyAPI", description: "A personal MCP (Model Context Protocol) server for securely storing and accessing API keys across projects using the macOS Keychain." },
    { name: "jordandalton/restcsv-mcp-server", description: "An MCP server for CSV files." },
    { name: "joshuarileydev/app-store-connect-mcp-server", description: "An MCP server to communicate with the App Store Connect API for iOS Developers" },
    { name: "joshuarileydev/simulator-mcp-server", description: "An MCP server to control iOS Simulators" },
    { name: "Jpisnice/shadcn-ui-mcp-server", description: "MCP server that gives AI assistants seamless access to shadcn/ui v4 components, blocks, demos, and metadata." },
    { name: "jsdelivr/globalping-mcp-server", description: "The Globalping MCP server provides users and LLMs access to run network tools like ping, traceroute, mtr, HTTP and DNS resolve from thousands of locations around the world." },
    { name: "kadykov/mcp-openapi-schema-explorer", description: "Token-efficient access to OpenAPI/Swagger specs via MCP Resources." },
    { name: "lamemind/mcp-server-multiverse", description: "A middleware server that enables multiple isolated instances of the same MCP servers to coexist independently with unique namespaces and configurations." },
    { name: "langfuse/mcp-server-langfuse", description: "MCP server to access and manage LLM application prompts created with Langfuse Prompt Management." },
    { name: "linw1995/nvim-mcp", description: "A MCP server to interact with Neovim" },
    { name: "lpigeon/ros-mcp-server", description: "The ROS MCP Server supports robot control by converting user-issued natural language commands into ROS or ROS2 control commands." },
    { name: "lpigeon/unitree-go2-mcp-server", description: "The Unitree Go2 MCP Server is a server built on the MCP that enables users to control the Unitree Go2 robot using natural language commands interpreted by a LLM." },
    { name: "ukkit/memcord", description: "A MCP server that keeps your chat history organized and searchable—with AI-powered summaries, secure memory, and full control." },
    { name: "mattjegan/swarmia-mcp", description: "Read-only MCP server to help gather metrics from Swarmia for quick reporting." },
    { name: "mobile-next/mobile-mcp", description: "MCP Server for Android/iOS application and device automation, development and app scraping. Simulator/Emulator/Physical devices like iPhone, Google Pixel, Samsung supported." },
    { name: "mrexodia/user-feedback-mcp", description: "Simple MCP Server to enable a human-in-the-loop workflow in tools like Cline and Cursor." },
    { name: "mumez/pharo-smalltalk-interop-mcp-server", description: "Pharo Smalltalk integration enabling code evaluation, class/method introspection, package management, test execution, and project installation for interactive development with Pharo images." },
    { name: "narumiruna/gitingest-mcp", description: "A MCP server that uses gitingest to convert any Git repository into a simple text digest of its codebase." },
    { name: "neilberkman/editorconfig_mcp", description: "Formats files using .editorconfig rules, acting as a proactive formatting gatekeeper to ensure AI-generated code adheres to project-specific formatting standards from the start." },
    { name: "OctoMind-dev/octomind-mcp", description: "lets your preferred AI agent create & run fully managed Octomind end-to-end tests from your codebase or other data sources like Jira, Slack or TestRail." },
    { name: "OpenZeppelin/contracts-wizard", description: "A Model Context Protocol (MCP) server that allows AI agents to generate secure smart contracts in multiples languages based on OpenZeppelin Wizard templates." },
    { name: "bgauryy/octocode-mcp", description: "AI-powered developer assistant that enables advanced research, analysis and discovery across GitHub and NPM realms in realtime." },
    { name: "opslevel/opslevel-mcp", description: "Official MCP Server for OpsLevel" },
    { name: "ooples/token-optimizer-mcp", description: "Intelligent token optimization achieving 95%+ reduction through caching, compression, and 80+ smart tools for API optimization, code analysis, and real-time monitoring." },
    { name: "picahq/mcp", description: "One MCP for all your integrations — powered by Pica, the infrastructure for intelligent, collaborative agents." },
    { name: "posthog/mcp", description: "An MCP server for interacting with PostHog analytics, feature flags, error tracking and more." },
    { name: "Pratyay/mac-monitor-mcp", description: "Identifies resource-intensive processes on macOS and provides performance improvement suggestions." },
    { name: "pskill9/website-downloader", description: "This MCP server provides a tool to download entire websites using wget. It preserves the website structure and converts links to work locally." },
    { name: "qainsights/jmeter-mcp-server", description: "JMeter MCP Server for performance testing" },
    { name: "qainsights/k6-mcp-server", description: "Grafana k6 MCP Server for performance testing" },
    { name: "qainsights/locust-mcp-server", description: "Locust MCP Server for performance testing" },
    { name: "QuantGeekDev/docker-mcp", description: "Docker container management and operations through MCP" },
    { name: "r-huijts/xcode-mcp-server", description: "Xcode integration for project management, file operations, and build automation" },
    { name: "ReAPI-com/mcp-openapi", description: "MCP server that lets LLMs know everything about your OpenAPI specifications to discover, explain and generate code/mock data" },
    { name: "reflagcom/mcp", description: "Flag features directly from chat in your IDE with Reflag." },
    { name: "Rootly-AI-Labs/Rootly-MCP-server", description: "MCP server for the incident management platform Rootly." },
    { name: "ryan0204/github-repo-mcp", description: "GitHub Repo MCP allow your AI assistants browse GitHub repositories, explore directories, and view file contents." },
    { name: "sammcj/mcp-package-version", description: "An MCP Server to help LLMs suggest the latest stable package versions when writing code." },
    { name: "sapientpants/sonarqube-mcp-server", description: "A Model Context Protocol (MCP) server that integrates with SonarQube to provide AI assistants with access to code quality metrics, issues, and quality gate statuses" },
    { name: "SDGLBL/mcp-claude-code", description: "An implementation of Claude Code capabilities using MCP, enabling AI code understanding, modification, and project analysis with comprehensive tool support." },
    { name: "sequa-ai/sequa-mcp", description: "Stop stitching context for Copilot and Cursor. With Sequa MCP, your AI tools know your entire codebase and docs out of the box." },
    { name: "snaggle-ai/openapi-mcp-server", description: "Connect any HTTP/REST API server using an Open API spec (v3)" },
    { name: "spacecode-ai/SpaceBridge-MCP", description: "Bring structure and preserve context in vibe coding by automatically tracking issues." },
    { name: "st3v3nmw/sourcerer-mcp", description: "MCP for semantic code search & navigation that reduces token waste" },
    { name: "stass/lldb-mcp", description: "A MCP server for LLDB enabling AI binary and core file analysis, debugging, disassembling." },
    { name: "storybookjs/addon-mcp", description: "Help agents automatically write and test stories for your UI components." },
    { name: "TencentEdgeOne/edgeone-pages-mcp", description: "An MCP service for deploying HTML content to EdgeOne Pages and obtaining a publicly accessible URL." },
    { name: "tgeselle/bugsnag-mcp", description: "An MCP server for interacting with Bugsnag" },
    { name: "Tommertom/awesome-ionic-mcp", description: "Your Ionic coding buddy enabled via MCP – build awesome mobile apps using React/Angular/Vue or even Vanilla JS!" },
    { name: "tipdotmd/tip-md-x402-mcp-server", description: "MCP server for cryptocurrency tipping through AI interfaces using x402 payment protocol and CDP Wallet." },
    { name: "tumf/mcp-text-editor", description: "A line-oriented text file editor. Optimized for LLM tools with efficient partial file access to minimize token usage." },
    { name: "utensils/mcp-nixos", description: "MCP server providing accurate information about NixOS packages, system options, Home Manager configurations, and nix-darwin macOS settings to prevent AI hallucinations." },
    { name: "vasayxtx/mcp-prompt-engine", description: "MCP server for managing and serving dynamic prompt templates using elegant and powerful text template engine." },
    { name: "vivekvells/mcp-pandoc", description: "MCP server for seamless document format conversion using Pandoc, supporting Markdown, HTML, PDF, DOCX (.docx), csv and more." },
    { name: "VSCode Devtools", description: "Connect to VSCode ide and use semantic tools like find_usages" },
    { name: "Webvizio/mcp", description: "Automatically converts feedback and bug reports from websites and web apps into actionable, context-enriched developer tasks. Delivered straight to your AI coding tools, the Webvizio MCP Server ensures your AI agent has all the data it needs to solve tasks with speed and accuracy." },
    { name: "WiseVision/mcp_server_ros_2", description: "MCP server for ROS2 enabling AI-driven robotics applications and services." },
    { name: "Wooonster/hocr_mcp_server", description: "A fastAPI-based FastMCP server with a Vue frontend that sends uploaded images to VLM via the MCP to quickly extract handwritten mathematical formulas as clean LaTeX code." },
    { name: "xcodebuild", description: "Build iOS Xcode workspace/project and feed back errors to llm." },
    { name: "XixianLiang/HarmonyOS-mcp-server", description: "Control HarmonyOS-next devices with AI through MCP. Support device control and UI automation." },
    { name: "xzq.xu/jvm-mcp-server", description: "An implementation project of a JVM-based MCP (Model Context Protocol) server." },
    { name: "yangkyeongmo@/mcp-server-apache-airflow", description: "MCP server that connects to Apache Airflow using official client." },
    { name: "yikakia/godoc-mcp-server", description: "Query Go package information on pkg.go.dev" },
    { name: "yiwenlu66/PiloTY", description: "AI pilot for PTY operations enabling agents to control interactive terminals with stateful sessions, SSH connections, and background process management" },
    { name: "YuChenSSR/mindmap-mcp-server", description: "A Model Context Protocol (MCP) server for generating a beautiful interactive mindmap." },
    { name: "YuChenSSR/multi-ai-advisor", description: "A Model Context Protocol (MCP) server that queries multiple Ollama models and combines their responses, providing diverse AI perspectives on a single question." },
    { name: "Yutarop/ros-mcp", description: "MCP server that supports ROS2 topics, services, and actions communication, and controls robots using natural language." },
    { name: "yWorks/mcp-typescribe", description: "MCP server that provides Typescript API information efficiently to the agent to enable it to work with untrained APIs" },
    { name: "zaizaizhao/mcp-swagger-server", description: "A Model Context Protocol (MCP) server that converts OpenAPI/Swagger specifications to MCP format, enabling AI assistants to interact with REST APIs through standardized protocol." },
    { name: "zcaceres/fetch-mcp", description: "An MCP server to flexibly fetch JSON, text, and HTML data" },
    { name: "zenml-io/mcp-zenml", description: "An MCP server to connect with your ZenML MLOps and LLMOps pipelines" },
    { name: "zillow/auto-mobile", description: "Tool suite built around an MCP server for Android automation for developer workflow and testing" },
  ];

  return (
    <div className="p-10">
      <h1 className="text-2xl font-bold">开发者工具</h1>
      <p className="mb-6">开发者工具类MCP服务器</p>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {mcpServers.map((server, index) => (
          <div key={index} className="border rounded-lg p-4 bg-gray-50 dark:bg-gray-800">
            <h3 className="font-semibold">{server.name}</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">{server.description}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

export default DeveloperToolsRouteComponent;