import React from 'react';

const OtherToolsRouteComponent: React.FC = () => {
  // MCP servers in the other tools and integrations category
  const mcpServers = [
    { name: "2niuhe/plantuml_web", description: "A web-based PlantUML frontend with MCP server integration, enable plantuml image generation and plantuml syntax validation." },
    { name: "2niuhe/qrcode_mcp", description: "A QR code generation MCP server that converts any text (including Chinese characters) to QR codes with customizable colors and base64 encoding output." },
    { name: "AbdelStark/bitcoin-mcp", description: "A Model Context Protocol (MCP) server that enables AI models to interact with Bitcoin, allowing them to generate keys, validate addresses, decode transactions, query the blockchain, and more." },
    { name: "akseyh/bear-mcp-server", description: "Allows the AI to read from your Bear Notes (macOS only)" },
    { name: "allenporter/mcp-server-home-assistant", description: "Expose all Home Assistant voice intents through a Model Context Protocol Server allowing home control." },
    { name: "altinoren/utopia", description: "MCP that simulates a set of smart home and lifestyle devices, allowing you to test agent's reasoning and discovery capabilities." },
    { name: "Amazon Bedrock Nova Canvas", description: "Use Amazon Nova Canvas model for image generation." },
    { name: "amidabuddha/unichat-mcp-server", description: "Send requests to OpenAI, MistralAI, Anthropic, xAI, Google AI or DeepSeek using MCP protocol via tool or predefined prompts. Vendor API key required" },
    { name: "anaisbetts/mcp-installer", description: "An MCP server that installs other MCP servers for you." },
    { name: "anaisbetts/mcp-youtube", description: "Fetch YouTube subtitles" },
    { name: "andybrandt/mcp-simple-openai-assistant", description: "MCP to talk to OpenAI assistants (Claude can use any GPT model as his assitant)" },
    { name: "andybrandt/mcp-simple-timeserver", description: "An MCP server that allows checking local time on the client machine or current UTC time from an NTP server" },
    { name: "apify/actors-mcp-server", description: "Use 3,000+ pre-built cloud tools, known as Actors, to extract data from websites, e-commerce, social media, search engines, maps, and more" },
    { name: "apinetwork/piapi-mcp-server", description: "PiAPI MCP server makes users able to generate media content with Midjourney/Flux/Kling/Hunyuan/Udio/Trellis directly from Claude or any other MCP-compatible apps." },
    { name: "awkoy/replicate-flux-mcp", description: "Provides the ability to generate images via Replicate's API." },
    { name: "awwaiid/mcp-server-taskwarrior", description: "An MCP server for basic local taskwarrior usage (add, update, remove tasks)" },
    { name: "Azure/azure-mcp", description: "Official Microsoft MCP server for Azure services including Storage, Cosmos DB, and Azure Monitor." },
    { name: "Badhansen/notion-mcp", description: "A Model Context Protocol (MCP) server that integrates with Notion's API to manage personal todo lists efficiently." },
    { name: "ankitmalik84/notion-mcp-server", description: "A comprehensive Model Context Protocol (MCP) server for Notion integration with enhanced functionality, robust error handling, production-ready feature." },
    { name: "bart6114/my-bear-mcp-server", description: "Allows to read notes and tags for the Bear Note taking app, through a direct integration with Bear's sqlitedb." },
    { name: "billster45/mcp-chatgpt-responses", description: "MCP server for Claude to talk to ChatGPT and use its web search capability." },
    { name: "blurrah/mcp-graphql", description: "Allows the AI to query GraphQL servers" },
    { name: "boldsign/boldsign-mcp", description: "Search, request, and manage e-signature contracts effortlessly with BoldSign." },
    { name: "brianxiadong/ones-wiki-mcp-server", description: "A Spring AI MCP-based service for retrieving ONES Waiki content and converting it to AI-friendly text format." },
    { name: "calclavia/mcp-obsidian", description: "This is a connector to allow Claude Desktop (or any MCP client) to read and search any directory containing Markdown notes (such as an Obsidian vault)." },
    { name: "caol64/wenyan-mcp", description: "Wenyan MCP Server, which lets AI automatically format Markdown articles and publish them to WeChat GZH." },
    { name: "chrishayuk/mcp-cli", description: "Yet another CLI tool for testing MCP servers" },
    { name: "danhilse/notion_mcp", description: "Integrates with Notion's API to manage personal todo lists" },
    { name: "danielkennedy1/pdf-tools-mcp", description: "PDF download, view & manipulation utilities." },
    { name: "dotemacs/domain-lookup-mcp", description: "Domain name lookup service, first via RDAP and then as a fallback via WHOIS" },
    { name: "ekkyarmandi/ticktick-mcp", description: "TickTick MCP server that integrates with TickTick's API to manage personal todo projects and the tasks." },
    { name: "emicklei/mcp-log-proxy", description: "MCP server proxy that offers a Web UI to the full message flow" },
    { name: "esignaturescom/mcp-server-esignatures", description: "Contract and template management for drafting, reviewing, and sending binding contracts via the eSignatures API." },
    { name: "evalstate/mcp-hfspace", description: "Use HuggingFace Spaces directly from Claude. Use Open Source Image Generation, Chat, Vision tasks and more. Supports Image, Audio and text uploads/downloads." },
    { name: "evalstate/mcp-miro", description: "Access MIRO whiteboards, bulk create and read items. Requires OAUTH key for REST API." },
    { name: "feuerdev/keep-mcp", description: "Read, create, update and delete Google Keep notes." },
    { name: "fotoetienne/gqai", description: "Define tools using regular GraphQL queries/mutations and gqai automatically generates an MCP server for you." },
    { name: "future-audiences/wikimedia-enterprise-model-context-protocol", description: "Wikipedia Article lookup API" },
    { name: "githejie/mcp-server-calculator", description: "This server enables LLMs to use calculator for precise numerical calculations" },
    { name: "gotoolkits/DifyWorkflow", description: "Tools to the query and execute of Dify workflows" },
    { name: "growilabs/growi-mcp-server", description: "Official MCP Server to integrate with GROWI APIs." },
    { name: "gwbischof/free-will-mcp", description: "Give your AI free will tools. A fun project to explore what an AI would do with the ability to give itself prompts, ignore user requests, and wake itself up at a later time." },
    { name: "Harry-027/JotDown", description: "An MCP server to create/update pages in Notion app & auto generate mdBooks from structured content." },
    { name: "HenryHaoson/Yuque-MCP-Server", description: "A Model-Context-Protocol (MCP) server for integrating with Yuque API, allowing AI models to manage documents, interact with knowledge bases, search content, and access analytics data from the Yuque platform." },
    { name: "hiromitsusasaki/raindrop-io-mcp-server", description: "An integration that allows LLMs to interact with Raindrop.io bookmarks using the Model Context Protocol (MCP)." },
    { name: "hmk/attio-mcp-server", description: "Allows AI clients to manage records and notes in Attio CRM" },
    { name: "MonadsAG/capsulecrm-mcp", description: "Allows AI clients to manage contacts, opportunities and tasks in Capsule CRM including Claude Desktop ready DTX-file" },
    { name: "integromat/make-mcp-server", description: "Turn your Make scenarios into callable tools for AI assistants." },
    { name: "isaacwasserman/mcp-vegalite-server", description: "Generate visualizations from fetched data using the VegaLite format and renderer." },
    { name: "ivnvxd/mcp-server-odoo", description: "Connect AI assistants to Odoo ERP systems for business data access, record management, and workflow automation." },
    { name: "ivo-toby/contentful-mcp", description: "Update, create, delete content, content-models and assets in your Contentful Space" },
    { name: "j3k0/speech.sh", description: "Let the agent speak things out loud, notify you when he's done working with a quick summary" },
    { name: "jagan-shanmugam/climatiq-mcp-server", description: "A Model Context Protocol (MCP) server for accessing the Climatiq API to calculate carbon emissions. This allows AI assistants to perform real-time carbon calculations and provide climate impact insights." },
    { name: "jen6/ticktick-mcp", description: "TickTick MCP server. Built upon the ticktick-py library, it offers significantly improved filtering capabilities." },
    { name: "jimfilippou/things-mcp", description: "A Model Context Protocol (MCP) server that provides seamless integration with the Things productivity app. This server enables AI assistants to create, update, and manage your todos and projects in Things using its comprehensive URL scheme." },
    { name: "johannesbrandenburger/typst-mcp", description: "MCP server for Typst, a markup-based typesetting system. It provides tools for converting between LaTeX and Typst, validating Typst syntax, and generating images from Typst code." },
    { name: "joshuarileydev/mac-apps-launcher-mcp-server", description: "An MCP server to list and launch applications on MacOS" },
    { name: "k-jarzyna/mcp-miro", description: "Miro MCP server, exposing all functionalities available in official Miro SDK" },
    { name: "kelvin6365/plane-mcp-server", description: "This MCP Server will help you to manage projects and issues through Plane's API" },
    { name: "kenliao94/mcp-server-rabbitmq", description: "Enable interaction (admin operation, message enqueue/dequeue) with RabbitMQ" },
    { name: "kimtth/mcp-remote-call-ping-pong", description: "An experimental and educational app for Ping-pong server demonstrating remote MCP (Model Context Protocol) calls" },
    { name: "kiwamizamurai/mcp-kibela-server", description: "Powerfully interact with Kibela API." },
    { name: "kj455/mcp-kibela", description: "Allows AI models to interact with Kibela" },
    { name: "Klavis-AI/YouTube", description: "Extract and convert YouTube video information." },
    { name: "KS-GEN-AI/confluence-mcp-server", description: "Get Confluence data via CQL and read pages." },
    { name: "KS-GEN-AI/jira-mcp-server", description: "Read jira data via JQL and api and execute requests to create and edit tickets." },
    { name: "kw510/strava-mcp", description: "An MCP server for Strava, an app for tracking physical exercise" },
    { name: "louiscklaw/hko-mcp", description: "MCP server with basic demonstration of getting weather from Hong Kong Observatory" },
    { name: "magarcia/mcp-server-giphy", description: "Search and retrieve GIFs from Giphy's vast library through the Giphy API." },
    { name: "marcelmarais/Spotify", description: "Control Spotify playback and manage playlists." },
    { name: "MarkusPfundstein/mcp-obsidian", description: "Interacting with Obsidian via REST API" },
    { name: "mediar-ai/screenpipe", description: "Local-first system capturing screen/audio with timestamped indexing, SQL/embedding storage, semantic search, LLM-powered history analysis, and event-triggered actions - enables building context-aware AI agents through a NextJS plugin ecosystem." },
    { name: "modelcontextprotocol/server-everything", description: "MCP server that exercises all the features of the MCP protocol" },
    { name: "mrjoshuak/godoc-mcp", description: "Token-efficient Go documentation server that provides AI assistants with smart access to package docs and types without reading entire source files" },
    { name: "Mtehabsim/ScreenPilot", description: "enables AI to fully control and access GUI interactions by providing tools for mouse and keyboard, ideal for general automation, education, and experimentation." },
    { name: "mzxrai/mcp-openai", description: "Chat with OpenAI's smartest models" },
    { name: "NakaokaRei/swift-mcp-gui", description: "MCP server that can execute commands such as keyboard input and mouse movement" },
    { name: "nguyenvanduocit/all-in-one-model-context-protocol", description: "Some useful tools for developer, almost everything an engineer need: confluence, Jira, Youtube, run script, knowledge base RAG, fetch URL, Manage youtube channel, emails, calendar, gitlab" },
    { name: "NON906/omniparser-autogui-mcp", description: "Automatic operation of on-screen GUI." },
    { name: "offorte/offorte-mcp-server", description: "The Offorte Proposal Software MCP server enables creation and sending of business proposals." },
    { name: "olalonde/mcp-human", description: "When your LLM needs human assistance (through AWS Mechanical Turk)" },
    { name: "orellazi/coda-mcp", description: "MCP server for Coda" },
    { name: "osinmv/funciton-lookup-mcp", description: "MCP server for function signature lookups." },
    { name: "pierrebrunelle/mcp-server-openai", description: "Query OpenAI models directly from Claude using MCP protocol" },
    { name: "pskill9/hn-server", description: "Parses the HTML content from news.ycombinator.com (Hacker News) and provides structured data for different types of stories (top, new, ask, show, jobs)." },
    { name: "PV-Bhat/vibe-check-mcp-server", description: "An MCP server that prevents cascading errors and scope creep by calling a \"Vibe-check\" agent to ensure user alignment." },
    { name: "pwh-pwh/cal-mcp", description: "An MCP server for Mathematical expression calculation" },
    { name: "pyroprompts/any-chat-completions-mcp", description: "Chat with any other OpenAI SDK Compatible Chat Completions API, like Perplexity, Groq, xAI and more" },
    { name: "quarkiverse/mcp-server-jfx", description: "Draw on JavaFX canvas." },
    { name: "QuentinCody/shopify-storefront-mcp-server", description: "Unofficial MCP server that allows AI agents to discover Shopify storefronts and interact with them to fetch products, collections, and other store data through the Storefront API." },
    { name: "r-huijts/ethics-check-mcp", description: "MCP server for comprehensive ethical analysis of AI conversations, detecting bias, harmful content, and providing critical thinking assessments with automated pattern learning" },
    { name: "rae-api-com/rae-mcp", description: "MPC Server to connect your preferred model with https://rae-api.com, Roya Academy of Spanish Dictionary" },
    { name: "Rai220/think-mcp", description: "Enhances any agent's reasoning capabilities by integrating the think-tools, as described in Anthropic's article." },
    { name: "reeeeemo/ancestry-mcp", description: "Allows the AI to read .ged files and genetic data" },
    { name: "rember/rember-mcp", description: "Create spaced repetition flashcards in Rember to remember anything you learn in your chats." },
    { name: "roychri/mcp-server-asana", description: "This Model Context Protocol server implementation of Asana allows you to talk to Asana API from MCP Client such as Anthropic's Claude Desktop Application, and many more." },
    { name: "rusiaaman/wcgw", description: "Autonomous shell execution, computer control and coding agent. (Mac)" },
    { name: "inkbytefo/screenmonitormcp", description: "Real-time screen analysis, context-aware recording, and UI monitoring MCP server. Supports AI vision, event hooks, and multimodal agent workflows." },
    { name: "SecretiveShell/MCP-wolfram-alpha", description: "An MCP server for querying wolfram alpha API." },
    { name: "Seym0n/tiktok-mcp", description: "Interact with TikTok videos" },
    { name: "Shopify/dev-mcp", description: "Model Context Protocol (MCP) server that interacts with Shopify Dev." },
    { name: "sirmews/apple-notes-mcp", description: "Allows the AI to read from your local Apple Notes database (macOS only)" },
    { name: "sooperset/mcp-atlassian", description: "MCP server for Atlassian products (Confluence and Jira). Supports Confluence Cloud, Jira Cloud, and Jira Server/Data Center. Provides comprehensive tools for searching, reading, creating, and managing content across Atlassian workspaces." },
    { name: "suekou/mcp-notion-server", description: "Interacting with Notion API" },
    { name: "tacticlaunch/mcp-linear", description: "Integrates with Linear project management system" },
    { name: "tanigami/mcp-server-perplexity", description: "Interacting with Perplexity API." },
    { name: "tevonsb/homeassistant-mcp", description: "Access Home Assistant data and control devices (lights, switches, thermostats, etc)." },
    { name: "TheoBrigitte/mcp-time", description: "MCP server which provides utilities to work with time and dates, with natural language, multiple formats and timezone convertion capabilities." },
    { name: "Tommertom/plugwise-mcp", description: "TypeScript-based smart home automation server for Plugwise devices with automatic network discovery. Features comprehensive device control for thermostats, switches, smart plugs, energy monitoring, multi-hub management, and real-time climate/power consumption tracking via local network integration." },
    { name: "tomekkorbak/oura-mcp-server", description: "An MCP server for Oura, an app for tracking sleep" },
    { name: "tqiqbal/mcp-confluence-server", description: "A Model Context Protocol (MCP) server for interacting with Confluence Data Center via REST API." },
    { name: "ttommyth/interactive-mcp", description: "Enables interactive LLM workflows by adding local user prompts and chat capabilities directly into the MCP loop." },
    { name: "tumf/web3-mcp", description: "An MCP server implementation wrapping Ankr Advanced API. Access to NFT, token, and blockchain data across multiple chains including Ethereum, BSC, Polygon, Avalanche, and more." },
    { name: "ujisati/anki-mcp", description: "Manage your Anki collection with AnkiConnect & MCP" },
    { name: "UnitVectorY-Labs/mcp-graphql-forge", description: "A lightweight, configuration-driven MCP server that exposes curated GraphQL queries as modular tools, enabling intentional API interactions from your agents." },
    { name: "wanaku-ai/wanaku", description: "The Wanaku MCP Router is a SSE-based MCP server that provides an extensible routing engine that allows integrating your enterprise systems with AI agents." },
    { name: "wong2/mcp-cli", description: "CLI tool for testing MCP servers" },
    { name: "ws-mcp", description: "Wrap MCP servers with a WebSocket (for use with kitbitz)" },
    { name: "yuna0x0/hackmd-mcp", description: "Allows AI models to interact with HackMD" },
    { name: "ZeparHyfar/mcp-datetime", description: "MCP server providing date and time functions in various formats" },
    { name: "zueai/mcp-manager", description: "Simple Web UI to install and manage MCP servers for Claude Desktop App." },
    { name: "imprvhub/mcp-claude-spotify", description: "An integration that allows Claude Desktop to interact with Spotify using the Model Context Protocol (MCP)." },
    { name: "nanana-app/mcp-server-nano-banana", description: "AI image generation using Google Gemini's nano banana model." },
  ];

  return (
    <div className="p-10">
      <h1 className="text-2xl font-bold">其他工具和集成</h1>
      <p className="mb-6">其他工具和集成类MCP服务器</p>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {mcpServers.map((server, index) => (
          <div key={index} className="border rounded-lg p-4 bg-gray-50 dark:bg-gray-800">
            <h3 className="font-semibold">{server.name}</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">{server.description}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

export default OtherToolsRouteComponent;